project_name: trackello
release:
  github:
    owner: klauern
    name: trackello
  name_template: '{{.Tag}}'
brew:
  commit_author:
    name: Nick Klauer
    email: klauer@gmail.com
  install: bin.install "trackello"
scoop:
  commit_author:
    name: Nick Klauer
    email: klauer@gmail.com
  bucket:
    owner: klauern
    name: trackello-bucket
  homepage: https://github.com/klauern/trackello
  description: Tracking your work in Trello from the command-line
  license: Apache
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  goarm:
  - "6"
  targets:
  - linux_amd64
  - linux_386
  - darwin_amd64
  - darwin_386
  - windows_amd64
  main: cmd/trackello/main.go
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: trackello
  lang: go
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE*
  - README*
  - CHANGELOG*
fpm:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcraft:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
sign:
  cmd: keybase
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
