codecov:
  branch: master
  bot: klauern
  notify:
    require_ci_to_pass: true
  ci:
    - !appveyor
    - wercker
  token: 0ce09c8c-a6f8-491e-92ba-ed1f6fa8ea5e
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 40.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
